name: PrintName  
on: push # 假设您想要在每次 push 时触发这个 workflow  
  
jobs:  
  print-name:  
    runs-on: ubuntu-latest # 指定在何种环境中运行这个 job  
    steps:  
      - name: Print a name  
        env: # 定义环境变量  
          name: "zhangsan" # 注意这里使用英文冒号  
        run: | # 定义要运行的命令  
          echo $name # 打印环境变量 name 的值
