name: hello-github-actions  
on:  
  push:  
    branches:  
      - master  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: checkout_actions  
        uses: actions/checkout@v2  
  
      - name: setup-node  
        uses: actions/setup-node@v1  
        with:  
          node-version: '14'  
  
      - name: npm install and build  
        run: |  
          npm install  
          npm run build  
  
      - name: Commit and Push  
        run: |  
          git config --global user.email "2735070081@qq.com"  
          git config --global user.name "l1l1z"  
          git add .  
          git commit -m "Updates made by Github Actions" -a  
          git push
        env:
          email: 2735070081@qq.com
